import StoryQuiz from '../components/StoryQuiz'
import PetHelp,{growthTitle} from '../components/PetHelp'
import Head from 'next/head'
import {useEffect,useRef,useState} from 'react'
import PetChat from '../components/PetChat'
import {PetLook} from '../components/GameControls'
import usePet from '../components/usePet'
import CATALOG from '../components/petCatalog.json'
import {careForPet,wearOutfit,unlocked} from '../components/petMemory'
const LABELS={study:'正在研究成語',eat:'點心時間',shy:'有點害羞',sleep:'正在做一個好夢',happy:'和你一起充電'}
export default function PetHome(){
 const store=usePet(),p=store?.profiles[store.active], [action,setAction]=useState('study'),[notice,setNotice]=useState(''),[closet,setCloset]=useState(false),[busy,setBusy]=useState(false),[help,setHelp]=useState(false),[storyQuiz,setStoryQuiz]=useState(false)
 const timer=useRef(null),dialog=useRef(null)
 useEffect(()=>{setAction(Math.random()<.3?'sleep':'study');return()=>clearTimeout(timer.current)},[])
 useEffect(()=>{if(closet)dialog.current?.showModal();else dialog.current?.close()},[closet])
 function care(kind){if(!p)return;clearTimeout(timer.current);setNotice(careForPet(kind));if(kind==='feed'&&!p.food)return;setAction(kind==='feed'?'eat':kind==='pat'?'shy':'happy');timer.current=setTimeout(()=>setAction('study'),5600)}
 function equip(id){if(wearOutfit(id)){setCloset(false);setNotice(id?`換好啦！今天用「${id}」的模樣陪你。`:'回到你最熟悉的鼎鼎。')}else setNotice('這套造型還沒解鎖，先一起學習吧。')}
 const owned=CATALOG.filter(c=>unlocked(p?.lessons[c.idiom]))
 return <><Head><title>鼎鼎的家｜成語穿越者</title></Head><main className="dd-home">
 <header className="dd-header"><a className="dd-key" href="/?view=challenge">← 返回</a><div className="dd-title"><span className="dd-status-dot"/><h1>鼎鼎的家</h1></div><button className="dd-key dd-help-trigger" onClick={()=>setHelp(true)} aria-label="養成說明">? 說明</button><div className="dd-stats"><span title="每 100 經驗升一級">Lv. {Math.floor((p?.xp||0)/100)+1} <small className="dd-growth-title">{growthTitle(p?.xp||0)}</small><progress max={100} value={(p?.xp||0)%100} aria-label="升級進度"/><small className="dd-next-level">距升級 {100-(p?.xp||0)%100} 經驗</small></span><span title="知識點心">🍪 {p?.food||0}</span><span title="親密度">♥ {p?.bond||0}<small className="dd-growth-title">{(p?.bond||0)>=100?'默契知己':(p?.bond||0)>=30?'熟悉夥伴':'新朋友'}</small></span></div></header>
 <section className="dd-room" aria-label="鼎鼎的像素典故研究室"><img className="dd-room-art" src="/images/dingding-home/room.png" alt="有典故壁畫、書桌、電腦與 AI 螢幕的像素小屋"/><div className="dd-room-label"><span/> {busy?'鼎鼎正在想怎麼回答你…':LABELS[action]}</div><div className={`dd-resident dd-${action}`}><picture><source media="(prefers-reduced-motion: reduce)" srcSet={`/images/dingding-home/${action}.png`}/><img src={`/images/dingding-home/${action}.gif`} alt={`鼎鼎${LABELS[action]}`}/></picture>{p?.outfit&&<span className="dd-outfit-pin" title={`${p.outfit}造型`}>{CATALOG.find(c=>c.idiom===p.outfit)?.emoji}</span>}</div><button className="dd-room-hotspot" onClick={()=>care('pat')} aria-label="摸摸鼎鼎（相知相惜）" title="相知相惜：摸摸鼎鼎"/><div className="dd-floor-label">典故研究室 · {p?.outfit||'初始造型'}</div></section>
 <section className="dd-console" aria-label="鼎鼎互動控制台"><nav className="dd-actions" aria-label="照顧鼎鼎"><button className="dd-key" onClick={()=>care('feed')} disabled={!p}><span>◈</span> 典故點心 <small>−1🍪 / +5♥</small></button><button className="dd-key" onClick={()=>care('pat')} disabled={!p}><span>♡</span> 相知相惜 <small>+2♥</small></button><button className="dd-key" onClick={()=>care('rest')} disabled={!p}><span>☾</span> 養精蓄銳 <small>+2♥</small></button><button className="dd-key" onClick={()=>setCloset(true)}><span>▦</span> 造型 <small>{owned.length}/40</small></button><button className="dd-key" onClick={()=>setStoryQuiz(true)}>典故切磋</button><a className="dd-key dd-learn" href="/">去學習 ↗</a></nav><PetChat notice={notice} action={action} onBusy={setBusy}/></section>
 </main><dialog ref={dialog} className="dd-closet" onCancel={()=>setCloset(false)} onClose={()=>setCloset(false)}><header><h2>典故造型櫃</h2><button className="dd-key" onClick={()=>setCloset(false)} aria-label="關閉造型櫃">✕</button></header><p>讀過典故，再完成四階段練習或挑戰答對兩次，即可解鎖。</p><button className="dd-key" onClick={()=>equip(null)}>原本的鼎鼎</button><div className="dd-wardrobe-grid">{CATALOG.map(c=>{const ready=unlocked(p?.lessons[c.idiom]);return <button className={`dd-outfit ${ready?'unlocked':''}`} key={c.id} onClick={()=>equip(c.idiom)} disabled={!ready}><PetLook size={72} outfit={c.idiom}/><strong>{c.idiom}</strong><small>{p?.outfit===c.idiom?'使用中':ready?'換上':'尚未解鎖'}</small><small>{p?.lessons[c.idiom]?.read?'✓ 已讀':'未讀典故'} · 練習 {Object.keys(p?.lessons[c.idiom]?.stages||{}).length}/4 · 挑戰 {Math.min(2,p?.lessons[c.idiom]?.challengeCorrect||0)}/2</small></button>})}</div></dialog><StoryQuiz open={storyQuiz} onClose={()=>setStoryQuiz(false)}/><PetHelp open={help} onClose={()=>setHelp(false)} profile={p}/></>
}
